# fly.toml app configuration file generated for lobe-fly-spring-river-9351 on 2024-02-24T14:26:10+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lobe-fly-spring-river-9351'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3210
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ENABLE_OAUTH_SSO = "1"